<a href="https://colab.research.google.com/github/oliviergentil/MAR_Explorer/blob/main/MAR_Explorer_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import mar_explorer as mar
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
mar.load_years([2021, 2022, 2023, 2024, 2025],4)

✓ MAR 2021, Chapter 4 loaded.
✓ MAR 2022, Chapter 4 loaded.
✓ MAR 2023, Chapter 4 loaded.
✓ MAR 2024, Chapter 4 loaded.
✓ MAR 2025, Chapter 4 already in memory.

In [ ]:
mar.list_tables(2025,4)

0 — Chart 1: EI service requests via different in-person service channels in 2024-25 *
1 — Image 1: EI Call Centre call volumes
2 — Image 2: Applications submitted using AppliWeb
3 — Chart 2: Preferred methods for completing EI reports
4 — Image 3: Documents accepted for electronic submission
5 — Chart 3: Applications received and claims processed
6 — Chart 4: Number of processing officers and EI experience
7 — Chart 5: Error rates (Claimant, Employer, Service Canada)
8 — Chart 6: Total net savings identified ($M) due to integrity activities
9 — Chart 7: 2024-25 EI issues most frequently requested for reconsideration
10 — Chart 8: Percentage of initial decisions reversed or changed following reconsideration
11 — Image 4: SST divisions
12 — Chart 9: 2024-25 adherence to the 45-day service standard for decisions following an appeal at the General Division, EI section (excluding groups)
13 — Chart 10: 2024-25 adherence to the 15-day service standard for decisions following a hearing at the General Division, EI section (excluding groups)
14 — Chart 11: Most common issues in appeals concluded at the General Division, EI Section in 2024-25
15 — Chart 12: 2024-25 outcomes of appeals to the General Division, EI section
16 — Chart 13: 2024-25 adherence to the 45-day service standard for leave to appeal decisions at the Appeal Division, EI section (excluding groups)
17 — Chart 14: 2024-25 adherence to the 150-day service standard for final decisions following permission to appeal at the Appeal Division, EI section (excluding groups)
18 — Chart 15: 2024-25 adherence to the 60-day service standard for final decisions following hearing at the Appeal Division, EI section
19 — Chart 16: 2024-25 outcomes of Appeal Division, EI section
20 — Chart 17: 2023-24 distribution of appellant representation types, as identified by the representatives

In [ ]:
mar.search("Applications received")

MAR 2025, Chapter 4
5 — Chart 3: Applications received and claims processed

MAR 2024, Chapter 4
5 — Chart 3 – Applications received and claims processed

In [ ]:
ei_reports_2025 = mar.show_table(2025, 4, 5)

5 — Chart 3: Applications received and claims processed

,Fiscal year,2020-21,2021-22,2022-23,2023-24,2024-25
0,Percentage of EI reports completed online,90.7,86.6,84.7,85.9,86.8
1,Percentage of EI reports completed on the phone,9.3,13.4,15.3,14.1,13.2

In [ ]:
ei_reports_2024 = mar.show_table(2024, 4, 5)

5 — Chart 3 – Applications received and claims processed

,Fiscal year,2019-20,2020-21,2021-22,2022-23,2023-24
0,Percentage of EI reports completed online,80.9,90.7,86.6,84.7,85.9
1,Percentage of EI reports completed on the phone,19.1,9.3,13.4,15.3,14.1